<?php

namespace Tests\Feature;

use App\Thread;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\Concerns\InteractsWithExceptionHandling;

class CreateThreadsTest extends TestCase
{
    use DatabaseMigrations, InteractsWithExceptionHandling;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_authenticated_user_can_create_new_forum_threads()
    {
        $this->singIn();

        $thread = make(Thread::class);

        $this->post('/threads', $thread->toArray());

        $this->get($thread->path())
            ->assertSee($thread->title)
            ->assertSee($thread->body);
    }

    public function test_guest_cannot_create_a_new_forum_thread()
    {
        $this->enableException()
            ->expectException('Illuminate\Auth\AuthenticationException');

        $thread = make(Thread::class);

        $this->post('/threads', $thread->toArray());
    }

    public function test_guest_cannot_go_to_create_thread_page()
    {
        $this->get('/threads/create')
            ->assertRedirect('/login');
    }
}
